version: "3.9"

services:
  server:
    build: .
    ports:
      - "8000:8080"
    env_file: .env
    depends_on:
      - redis
      - postgres
    networks:
      - default

  celery_worker:
    build: .
    command: celery -A server.core.tasks.base.main:make worker --loglevel=info --concurrency=2
    env_file: .env
    depends_on:
      - redis
      - postgres
    networks:
      - default

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-space:/var/lib/redis/data
    networks:
      - default

  postgres:
    image: postgres:18.3-alpine3.23
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres-space:/var/lib/postgresql/data
    networks:
      - default

volumes:
  redis-space:
  postgres-space:

networks:
  default:
