FROM python:3.14-alpine3.23

WORKDIR /server

COPY ./requirements.txt .

COPY ./server .

ENV SERVER_HOST=127.0.0.1
ENV SERVER_PORT=8000
ENV LOOP_MASTER=asyncio

EXPOSE 8000

RUN pip install --no-cache-dir -r requirements.txt

RUN ./setup.sh
