"""init

Revision ID: 893db2b91a6d
Revises: 
Create Date: 2026-01-15 17:14:57.258584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '893db2b91a6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('type', postgresql.ENUM('INFO', 'ERROR', 'WARNING', 'DEBUG' 'NOT_TYPE', name='log_type'), nullable=False),
    sa.Column('level', postgresql.ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'VERY_LOW', name='log_level'), nullable=False),
    sa.Column('status', postgresql.ENUM('SUCCESS', 'FAILURE', 'PENDING', 'NOT_STATUS' 'NOT_LEVEL', name='log_status'), nullable=False),
    sa.Column('action', postgresql.ENUM('CREATE', 'READ', 'UPDATE', 'DELETE', 'NOT_REGISTERED', name='log_action'), nullable=False),
    sa.Column('assistant_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('final_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('scopes',
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.PrimaryKeyConstraint('scope_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('groupscopelink',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.scope_id'], ),
    sa.PrimaryKeyConstraint('group_id', 'scope_id')
    )
    op.create_table('usergrouplink',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('userscopelink',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.scope_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'scope_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userscopelink')
    op.drop_table('usergrouplink')
    op.drop_table('groupscopelink')
    op.drop_table('users')
    op.drop_table('scopes')
    op.drop_table('logs')
    op.drop_table('groups')
    # ### end Alembic commands ###
